const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1586186779000,
      duration: 7200000,
      id: '269891185',
      name: 'IBM Masterclass & Hackathon: AI Explainability',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588316400000,
      local_date: '2020-07-01',
      local_time: '09:00',
      updated: 1586186779000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      is_online_event: false,
      group: {
        created: 1400181332000,
        name: 'Big Data Developers in Munich',
        id: 14476282,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Big-Data-Developers-in-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/269891185/',
      description: '<p>Go beyond the code, advance towards responsible and trustworthy AI. Begins March 27, 2020 and ends May 1, 2020. This is a free on-line webinar that can be accessed at any time.</p> <p>REGISTER HERE FOR THIS FREE COURSE &amp; EVENT: ibm.biz/AIExplainability</p> <p>Take our free masterclass and then apply your new skills in the online Hackathon. Come learn new open-source and IBM data science tools like AIX360 and Lale. As well as, how to explain your model to any stakeholder and how to integrate explainable workflows.</p> <p>MASTERCLASS<br/>Quickly learn new data science concepts with this free 90-minute micro-course.</p> <p>HACKATHON<br/>Apply these new concepts by creating your own project to showcase and compete for the $8,000 prizepool and an IBM skill badge.</p> <p>MENTORSHIP<br/>Connect 1:1 with IBM data science experts for help and guidance on your project.</p> <p>WHO IS THIS FOR?<br/>All Data Scientists, AI &amp; ML Devs and Engineers, Startups and Enterprise</p> <p>WHY EXPLAINABILITY?<br/>Explainability is the ability for data scientists to produce applicable results for their peers, managers, and end-users. Can your results be understood and applied by other data scientists and stakeholders? It is up to you as a data scientist to use your business knowledge, mathematical, and programmatic skills to communicate your findings and methods. Explainability is an important tool used to make your reasoning behind each decision transparent and repeatable.</p> <p>In this course, learn the importance of building an explainability workflow and how to implement these practices from the beginning. Then, using your new skills and tools, apply what you have learned by submitting your own project. Each submission for the hackathon will have a chance at cash prizes during the 6-week competition.<br/>-------------------------------------------------</p> <p>REGISTER HERE FOR THIS FREE COURSE &amp; EVENT: ibm.biz/AIExplainability</p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1584390889000,
      duration: 14400000,
      id: '269466550',
      name: '3. agiles PM-Trendforum 2020 (digital) am 25.06.2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593100800000,
      local_date: '2020-06-25',
      local_time: '18:00',
      updated: 1586174006000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      is_online_event: false,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466550/',
      description: '<p>Agenda:</p> <p>18:00 Uhr – Begrüßung, Einleitung, Infos zum Ablauf</p> <p>18:15 Uhr – Vortrag 1: -&gt; „Office 365 –Professionelles Arbeiten im Homeoffice: Wie können die Office 365 und Edison 365 Apps ideal für das Arbeiten im Homeoffice genutzt werden? – Digitaler Arbeitsplatz der Zukunft in Corona Zeiten</p> <p>Vortrag Herr Andreas Hock, Partner 3Pworx GmbH</p> <p>\'Aufgrund der derzeitigen Corona Krise muss rasch ein digitaler Arbeitsplatz geschaffen werden – und zwar im Homeoffice, der allen Anforderungen genügt\'</p> <p>Millionen von Personen in Deutschland wurden zum Arbeiten ins Homeoffice geschickt. Wie kann der Spagat gelingen?<br/>Eine der führenden professionellen Lösungen, um effizient und professionell vom Homeoffice aus arbeitsfähig zu sein ist Office 365.<br/>Office 365 bietet hier vor allem interessante Lösungen und Apps aus dem Bereich der digitalen Zusammenarbeit, wie MS Teams, MS Planner, MS Power BI.</p> <p>Agile Methoden für Projekte werden ebenfalls verstärkt unterstützt.<br/><a href=\'https://3pworx.com/projektmanagement-mit-office-365/\' class=\'linkified\'>https://3pworx.com/projektmanagement-mit-office-365/</a></p> <p>Dieses Paket kann im Homeoffice durch Lösungen aus dem Bereich Ideenmanagement, Business Cases und Projekt-Kollaboration mit den fertigen Edison 365 Produktlösungen intelligent und nachhaltig erweitert werden.</p> <p>Die nahtlose Integration ins Office 365 Umfeld ist sehr einfach darstellbar. Weitere Schnittstellen zu MS Teams, usw. sind schlüsselfertig.</p> <p><a href=\'https://3pworx.com/edison-365/\' class=\'linkified\'>https://3pworx.com/edison-365/</a></p> <p>In diesem Webinar schildern wie Ihnen einige Anwendungsfälle, wie Sie schnell Office 365 ideal fürs Homeoffice nutzen können uns wir geben Ihnen einen interessanten Einblick der Erweiterung mit der Edison 365 Toolsuite, um hier einen zusätzlichen Mehrwert zu erhalten.</p> <p>19:15 Uhr – Vortrag 2: „Erfolgreich handeln in der Corona Krise – Funktionierende Managementprinzipien</p> <p>Vortrag von Herrn Prof. Dr. Komus</p> <p>Die aktuelle Corona-Krise schüttelt Wirtschaft, Management und Privatleben grundlegend durcheinander. Gute Entscheidungen sind schwierig – Sicherheit ist nicht zu haben.</p> <p>Trotzdem oder besser gerade deswegen gilt es, zu reflektieren, welche Entscheidungsmuster und Managementprinzipien in welchem Kontext funktionieren.</p> <p>Um die aktuellen Herausforderungen zu managen reichen selbst agile Methoden wie Scrum so wie sie meist gelebt werden nicht aus.</p> <p>Handlungsmuster für das komplex-chaotische Umfeld wie „MaxAgil“ (die pragmatische Maximierung agiler Prinzipien) oder „Effectuation“ versprechen bessere Ergebnisse. Gleichwohl gilt es auch in der Corona-Krise differenziert sinnvolle Lösungsansätze zu entwickeln. Der Beitrag zeigt wie das funktionieren kann und welche Schritte zu gehen sind.<br/>Prof. Dr. Ayelt Komus ist seit langem Experten und Vordenker für erfolgreiches Management bei Unsicherheit. Es hat früh die Potenziale und Anwendungsfelder und Grenzen agiler Methoden aufgezeigt. Seine Schwerpunkte sind agile und hybride Methoden auf Ebene von Projektportfolio, Programm und Unternehmen (Scaled Agile).</p> <p>20:15 Uhr – Vortrag 3: „Hybrides Projektmanagement – Vorstellung der Studienergebnisse</p> <p>Vortrag von Herrn Gregor Diem</p> <p>Seit mehr als einem Jahr forscht Gregor Diem an der Edinburgh Business School, Schottland, UK, an dem Thema hybrides Projektmanagement.</p> <p>Ziel dieser Studie ist es, ein besseres Verständnis des hybriden Projektmanagements zu erlangen und den jüngsten Trend in dieser Disziplin zu untersuchen, bei dem agile und traditionelle Projektmanagementpraktiken kombiniert werden. Daher ist auch das Ziel dieser Studie mehr über diesen Trend und wie dieser in der Praxis angewendet wird zu erfahren.</p> <p>Die Umfrage kann über folgenden Link aufgerufen werden: <a href=\'https://hwsml.eu.qualtrics.com/jfe/form/SV_2tyWt5wjIOYDBTD\' class=\'linkified\'>https://hwsml.eu.qualtrics.com/jfe/form/SV_2tyWt5wjIOYDBTD</a></p> <p>Erste Ergebnisse werden im agilen Trendforum gigital am Do. [masked] vorgestellt. Über eine rege Umfrageteilnahme und anschließender Diskussion im agilen Trendforum würden wir uns sehr freuen.</p> <p>21:30 Uhr: Q&amp;A</p> <p>Ca. 22:00 Uhr - Ende des 3Pworx 3. Agilen Trendforums Juni 2020 digital</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1586254041000,
      duration: 3600000,
      id: '269906778',
      name: 'PRACTICING GERMAN MEETUP B1',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1587488400000,
      local_date: '2020-04-21',
      local_time: '19:00',
      updated: 1586254041000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      is_online_event: false,
      group: {
        created: 1553169681000,
        name: 'Foreigners Feeling Comfortable In Munich',
        id: 31442074,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Foreigners-Feeling-Comfortable-In-Munich',
        who: 'Miembros',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Foreigners-Feeling-Comfortable-In-Munich/events/269906778/',
      description: '<p>Join our meeting in Zoom:<br/><a href=\'https://us04web.zoom.us/j/2953797303\' class=\'linkified\'>https://us04web.zoom.us/j/2953797303</a><br/>----------------</p> <p>We meet online to get to know each other and talk in German.<br/>This Meetup is for German learner level around B1.<br/>I\'m a professional German teacher, so you can also ask me questions and I will also explain you some things.</p> <p>THIS IS FOR YOU:<br/>If you want to USE the time to practice your German skills, learn also something new and meet new people. You can create learning partners or stay in touch afterwards.<br/>If you have a German level around B1.</p> <p>This is a offer of LANGUAGE SUCCESS<br/>Language Success - Mit Sprache zum Erfolg<br/>www.languagesuccess.org</p> ',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
}

const unmountedMockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1586186779000,
      duration: 7200000,
      id: '269891185',
      name: 'IBM Masterclass & Hackathon: AI Explainability',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588316400000,
      local_date: '2020-05-01',
      local_time: '09:00',
      updated: 1586186779000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      is_online_event: false,
      group: {
        created: 1400181332000,
        name: 'Big Data Developers in Munich',
        id: 14476282,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Big-Data-Developers-in-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/269891185/',
      description: '<p>Go beyond the code, advance towards responsible and trustworthy AI. Begins March 27, 2020 and ends May 1, 2020. This is a free on-line webinar that can be accessed at any time.</p> <p>REGISTER HERE FOR THIS FREE COURSE &amp; EVENT: ibm.biz/AIExplainability</p> <p>Take our free masterclass and then apply your new skills in the online Hackathon. Come learn new open-source and IBM data science tools like AIX360 and Lale. As well as, how to explain your model to any stakeholder and how to integrate explainable workflows.</p> <p>MASTERCLASS<br/>Quickly learn new data science concepts with this free 90-minute micro-course.</p> <p>HACKATHON<br/>Apply these new concepts by creating your own project to showcase and compete for the $8,000 prizepool and an IBM skill badge.</p> <p>MENTORSHIP<br/>Connect 1:1 with IBM data science experts for help and guidance on your project.</p> <p>WHO IS THIS FOR?<br/>All Data Scientists, AI &amp; ML Devs and Engineers, Startups and Enterprise</p> <p>WHY EXPLAINABILITY?<br/>Explainability is the ability for data scientists to produce applicable results for their peers, managers, and end-users. Can your results be understood and applied by other data scientists and stakeholders? It is up to you as a data scientist to use your business knowledge, mathematical, and programmatic skills to communicate your findings and methods. Explainability is an important tool used to make your reasoning behind each decision transparent and repeatable.</p> <p>In this course, learn the importance of building an explainability workflow and how to implement these practices from the beginning. Then, using your new skills and tools, apply what you have learned by submitting your own project. Each submission for the hackathon will have a chance at cash prizes during the 6-week competition.<br/>-------------------------------------------------</p> <p>REGISTER HERE FOR THIS FREE COURSE &amp; EVENT: ibm.biz/AIExplainability</p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1584390889000,
      duration: 14400000,
      id: '269466550',
      name: '3. agiles PM-Trendforum 2020 (digital) am 25.06.2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593100800000,
      local_date: '2020-06-25',
      local_time: '18:00',
      updated: 1586174006000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      is_online_event: false,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466550/',
      description: '<p>Agenda:</p> <p>18:00 Uhr – Begrüßung, Einleitung, Infos zum Ablauf</p> <p>18:15 Uhr – Vortrag 1: -&gt; „Office 365 –Professionelles Arbeiten im Homeoffice: Wie können die Office 365 und Edison 365 Apps ideal für das Arbeiten im Homeoffice genutzt werden? – Digitaler Arbeitsplatz der Zukunft in Corona Zeiten</p> <p>Vortrag Herr Andreas Hock, Partner 3Pworx GmbH</p> <p>\'Aufgrund der derzeitigen Corona Krise muss rasch ein digitaler Arbeitsplatz geschaffen werden – und zwar im Homeoffice, der allen Anforderungen genügt\'</p> <p>Millionen von Personen in Deutschland wurden zum Arbeiten ins Homeoffice geschickt. Wie kann der Spagat gelingen?<br/>Eine der führenden professionellen Lösungen, um effizient und professionell vom Homeoffice aus arbeitsfähig zu sein ist Office 365.<br/>Office 365 bietet hier vor allem interessante Lösungen und Apps aus dem Bereich der digitalen Zusammenarbeit, wie MS Teams, MS Planner, MS Power BI.</p> <p>Agile Methoden für Projekte werden ebenfalls verstärkt unterstützt.<br/><a href=\'https://3pworx.com/projektmanagement-mit-office-365/\' class=\'linkified\'>https://3pworx.com/projektmanagement-mit-office-365/</a></p> <p>Dieses Paket kann im Homeoffice durch Lösungen aus dem Bereich Ideenmanagement, Business Cases und Projekt-Kollaboration mit den fertigen Edison 365 Produktlösungen intelligent und nachhaltig erweitert werden.</p> <p>Die nahtlose Integration ins Office 365 Umfeld ist sehr einfach darstellbar. Weitere Schnittstellen zu MS Teams, usw. sind schlüsselfertig.</p> <p><a href=\'https://3pworx.com/edison-365/\' class=\'linkified\'>https://3pworx.com/edison-365/</a></p> <p>In diesem Webinar schildern wie Ihnen einige Anwendungsfälle, wie Sie schnell Office 365 ideal fürs Homeoffice nutzen können uns wir geben Ihnen einen interessanten Einblick der Erweiterung mit der Edison 365 Toolsuite, um hier einen zusätzlichen Mehrwert zu erhalten.</p> <p>19:15 Uhr – Vortrag 2: „Erfolgreich handeln in der Corona Krise – Funktionierende Managementprinzipien</p> <p>Vortrag von Herrn Prof. Dr. Komus</p> <p>Die aktuelle Corona-Krise schüttelt Wirtschaft, Management und Privatleben grundlegend durcheinander. Gute Entscheidungen sind schwierig – Sicherheit ist nicht zu haben.</p> <p>Trotzdem oder besser gerade deswegen gilt es, zu reflektieren, welche Entscheidungsmuster und Managementprinzipien in welchem Kontext funktionieren.</p> <p>Um die aktuellen Herausforderungen zu managen reichen selbst agile Methoden wie Scrum so wie sie meist gelebt werden nicht aus.</p> <p>Handlungsmuster für das komplex-chaotische Umfeld wie „MaxAgil“ (die pragmatische Maximierung agiler Prinzipien) oder „Effectuation“ versprechen bessere Ergebnisse. Gleichwohl gilt es auch in der Corona-Krise differenziert sinnvolle Lösungsansätze zu entwickeln. Der Beitrag zeigt wie das funktionieren kann und welche Schritte zu gehen sind.<br/>Prof. Dr. Ayelt Komus ist seit langem Experten und Vordenker für erfolgreiches Management bei Unsicherheit. Es hat früh die Potenziale und Anwendungsfelder und Grenzen agiler Methoden aufgezeigt. Seine Schwerpunkte sind agile und hybride Methoden auf Ebene von Projektportfolio, Programm und Unternehmen (Scaled Agile).</p> <p>20:15 Uhr – Vortrag 3: „Hybrides Projektmanagement – Vorstellung der Studienergebnisse</p> <p>Vortrag von Herrn Gregor Diem</p> <p>Seit mehr als einem Jahr forscht Gregor Diem an der Edinburgh Business School, Schottland, UK, an dem Thema hybrides Projektmanagement.</p> <p>Ziel dieser Studie ist es, ein besseres Verständnis des hybriden Projektmanagements zu erlangen und den jüngsten Trend in dieser Disziplin zu untersuchen, bei dem agile und traditionelle Projektmanagementpraktiken kombiniert werden. Daher ist auch das Ziel dieser Studie mehr über diesen Trend und wie dieser in der Praxis angewendet wird zu erfahren.</p> <p>Die Umfrage kann über folgenden Link aufgerufen werden: <a href=\'https://hwsml.eu.qualtrics.com/jfe/form/SV_2tyWt5wjIOYDBTD\' class=\'linkified\'>https://hwsml.eu.qualtrics.com/jfe/form/SV_2tyWt5wjIOYDBTD</a></p> <p>Erste Ergebnisse werden im agilen Trendforum gigital am Do. [masked] vorgestellt. Über eine rege Umfrageteilnahme und anschließender Diskussion im agilen Trendforum würden wir uns sehr freuen.</p> <p>21:30 Uhr: Q&amp;A</p> <p>Ca. 22:00 Uhr - Ende des 3Pworx 3. Agilen Trendforums Juni 2020 digital</p> ',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
}

export { mockEvents, unmountedMockEvents };